name = "course-planner"
version = "0.1.0"
defaultTargets = ["course_planner"]

[[require]]
name = "mlml"
git = "git@github.com:gmcninch-prof/mlml"
rev = "main"

[[require]]
name = "markdown"
git = "https://github.com/gmcninch-prof/lean4-markdown"
rev = "main"

[[lean_lib]]
name = "CoursePlanner"

[[lean_exe]]
name = "course_planner"
root = "Main"
