
  Semester {
    ay = "AY2025-2026"
    semId = Spring
    semesterDescr = "Spring 2026"
    
    semesterDates = Range { start = "2026-01-14"
    		            end = "2026-04-27"
  	  }
    
    finalsDates = Range { start = "2026-05-01"
    		  	  end = "2026-05-08"
  	}
    
    rpDates = Range { start = "2026-04-28"
    		                 end = "2026-04-30"
                               }
    
    exceptions = [
      Holiday { descr = "MLK Day"
                date =  "2026-01-19" }
      Admin   { type = "Academic Date"
                descr = "Last day to add a course"
                date =  "2026-01-21"
              }
      Holiday { descr = "Presidents' Day"
                date =  "2026-02-16"
              }
      Admin   { type = "Academic Date"
                descr = "Last day to drop a course without record"
                date =  "2026-02-18"
              }
      AltDow  { descr = "Monday schedule"
                date =  "2026-01-21"
                dow = Mon
              }
      AltDow  { descr = "Monday schedule"
                date =  "2026-02-19"
                dow = Mon
              }
      Holiday { descr = "Spring Break"
                date = Range { start = "2026-03-14"
                               end = "2026-03-22"
                             }
              }
      Admin   { type = "Academic Date"
                descr = "Last day to withdraw from a course with W"
                date =  "2026-04-01"
              }
      Admin   { type = "Academic Date"
                descr = "Last day to select Pass/Fail Option"
                date =  "2026-04-01"
              }
      Holiday { descr = "Patriots' Day"
                date =  "2026-04-20"
     	      }
      Admin   { type = "Academic Date"
                descr = "Reading Period"
                date = Range { start = "2026-04-28"
                         end = "2026-04-30"
     		     }
              }
      Admin   { type = "Academic Date"
                descr = "Final Exam Period"
                date = Range { start = "2026-05-01"
  	                       end = "2026-05-08"
                             }
              }
    ]
  }