;; Time-stamp: <2026-04-20 Mon 16:28 EDT - george@valhalla>
  Semester {
    ay = "AY2025-2026"
    semId = Fall
    semesterDescr = "Fall 2025"
      
    semesterDates = Range { start = "2025-09-02"
                            stop = "2025-12-08"
                          }
      
    finalsDates   = Range { start = "2025-12-11"
                            stop = "2025-12-18"
                          }
      
    rpDates = Range { start = "2025-12-09"
                      stop =  "2025-12-09"
                    }
      
    exceptions = [
      Admin   { type = "Academic Date"
                descr = "Last day to add"
                date = "2025-09-09"
              }
      Holiday { descr = "Indigenous Peoples' Day"
                date =  "2025-10-13"
              }
      Admin   { type = "Academic Date"
                descr = "Last day to drop without record"
                date = "2025-10-07"
              }
      Holiday { descr = "Veterans' Day"
                date =  "2025-11-11"
              }
      Admin   { type = "Academic Date"
                descr = "Last day to withdraw with W"
                date =  "2025-11-12"
              }
      Admin   { type = "Academic Date"
                descr = "Last day to select PASS/FAIL option"
                date =  "2025-11-12"
              }
      Holiday { descr = "Thanksgiving Holiday"
                date = Range { start = "2025-11-26"
                               stop = "2025-11-28"
                             }
              }
      Admin   { type = "Academic Date"
                descr = "Reading Period"
                date = Range { start = "2025-12-09"
                               stop = "2025-12-09"
  		    }
              }
      Admin   { type = "Academic Date"
                descr = "Final Exams"
                date = Range { start = "2025-12-11"
                               stop = "2025-12-18"
  		    }
              }
    ]
  }

